/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectSDNL;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class GuiMenuAwal extends javax.swing.JFrame {

    DataKost datPen = new DataKost();

    DefaultTableModel tableModel;

    public GuiMenuAwal() {
        initComponents();
        hideComponent();
        tambahDataKost();
        tambahDataKamarKost();
        tambahDataPenyewaMenyewa();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        panelPendapatan = new javax.swing.JPanel();
        lblPendapatan = new javax.swing.JLabel();
        lblTangga = new javax.swing.JLabel();
        lblWaktu = new javax.swing.JLabel();
        lblCatatan = new javax.swing.JLabel();
        txtPendapatan = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        txtWaktu = new javax.swing.JTextField();
        txtCatatan = new javax.swing.JTextField();
        btnInput = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        panelPengeluaran = new javax.swing.JPanel();
        lblPendapatan1 = new javax.swing.JLabel();
        lblLuarTanggal = new javax.swing.JLabel();
        lblLuarWaktu = new javax.swing.JLabel();
        lblLuarCatatan = new javax.swing.JLabel();
        txtPengeluaran = new javax.swing.JTextField();
        txtLuarTanggal = new javax.swing.JTextField();
        txtLuarWaktu = new javax.swing.JTextField();
        txtLuarCatatan = new javax.swing.JTextField();
        btnInput1 = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lblJudul2 = new javax.swing.JLabel();
        panelCari = new javax.swing.JPanel();
        rbPengeluaran = new javax.swing.JRadioButton();
        rbPendapatan = new javax.swing.JRadioButton();
        txtCari = new javax.swing.JTextField();
        btnCari_Cari = new javax.swing.JButton();
        lblCariPendapatan = new javax.swing.JLabel();
        lblCari = new javax.swing.JLabel();
        lblCariTanggal = new javax.swing.JLabel();
        lblCariWaktu = new javax.swing.JLabel();
        txtCariPendapatan = new javax.swing.JTextField();
        txtCariCatatan = new javax.swing.JTextField();
        txtCariTanggal = new javax.swing.JTextField();
        txtCariWaktu = new javax.swing.JTextField();
        lblCariCatatan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCariPEngeluaran = new javax.swing.JTextField();
        lblCariPengeluaran = new javax.swing.JLabel();
        panelAwal = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblJudul1 = new javax.swing.JLabel();
        panelHapus = new javax.swing.JPanel();
        lblHapusPendapatan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblHapusTanggal = new javax.swing.JLabel();
        txtHapusPengeluaran = new javax.swing.JTextField();
        txtHapusPendapatan = new javax.swing.JTextField();
        lblHapusPengeluaran = new javax.swing.JLabel();
        txtHapusTanggal = new javax.swing.JTextField();
        txtHapusWaktu = new javax.swing.JTextField();
        lblHapusWaktu = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelHapus = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblHapusCatatan = new javax.swing.JLabel();
        txtHapusCatatan = new javax.swing.JTextField();
        panelTampil = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabelKosong = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnPendapatan = new javax.swing.JButton();
        btnPengeluaran = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 65, 95));

        jLayeredPane3.setMinimumSize(new java.awt.Dimension(533, 356));

        panelPendapatan.setBackground(new java.awt.Color(255, 255, 255));
        panelPendapatan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPendapatan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPendapatan.setMinimumSize(new java.awt.Dimension(372, 356));
        panelPendapatan.setName(""); // NOI18N
        panelPendapatan.setPreferredSize(new java.awt.Dimension(533, 356));
        panelPendapatan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPendapatan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPendapatan.setLabelFor(txtPendapatan);
        lblPendapatan.setText("Pendapatan");
        panelPendapatan.add(lblPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        lblTangga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTangga.setLabelFor(txtTanggal);
        lblTangga.setText("Tanggal");
        lblTangga.setToolTipText("");
        panelPendapatan.add(lblTangga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lblWaktu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblWaktu.setLabelFor(txtWaktu);
        lblWaktu.setText("Waktu");
        panelPendapatan.add(lblWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lblCatatan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCatatan.setLabelFor(txtCatatan);
        lblCatatan.setText("Catatan");
        panelPendapatan.add(lblCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtPendapatan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPendapatanFocusLost(evt);
            }
        });
        panelPendapatan.add(txtPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 380, -1));

        txtTanggal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTanggalFocusLost(evt);
            }
        });
        panelPendapatan.add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 380, -1));
        panelPendapatan.add(txtWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 380, -1));

        txtCatatan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCatatanFocusLost(evt);
            }
        });
        panelPendapatan.add(txtCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 380, -1));

        btnInput.setBackground(new java.awt.Color(255, 255, 255));
        btnInput.setForeground(new java.awt.Color(0, 153, 0));
        btnInput.setText("Input");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        panelPendapatan.add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 75, -1));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setForeground(new java.awt.Color(204, 153, 0));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        panelPendapatan.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 75, -1));

        jPanel1.setBackground(new java.awt.Color(90, 90, 205));
        jPanel1.setForeground(new java.awt.Color(23, 65, 127));

        lblJudul.setBackground(new java.awt.Color(255, 255, 255));
        lblJudul.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Pendapatan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblJudul)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelPendapatan.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 80));

        panelPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        panelPengeluaran.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPengeluaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPengeluaran.setMinimumSize(new java.awt.Dimension(372, 356));
        panelPengeluaran.setName(""); // NOI18N
        panelPengeluaran.setPreferredSize(new java.awt.Dimension(533, 356));
        panelPengeluaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPendapatan1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPendapatan1.setLabelFor(txtPendapatan);
        lblPendapatan1.setText("Pengeluaran");
        panelPengeluaran.add(lblPendapatan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        lblLuarTanggal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLuarTanggal.setLabelFor(txtTanggal);
        lblLuarTanggal.setText("Tanggal");
        lblLuarTanggal.setToolTipText("");
        panelPengeluaran.add(lblLuarTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lblLuarWaktu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLuarWaktu.setLabelFor(txtWaktu);
        lblLuarWaktu.setText("Waktu");
        panelPengeluaran.add(lblLuarWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lblLuarCatatan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLuarCatatan.setLabelFor(txtCatatan);
        lblLuarCatatan.setText("Catatan");
        panelPengeluaran.add(lblLuarCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtPengeluaran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPengeluaranFocusLost(evt);
            }
        });
        panelPengeluaran.add(txtPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 380, -1));

        txtLuarTanggal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLuarTanggalFocusLost(evt);
            }
        });
        txtLuarTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuarTanggalActionPerformed(evt);
            }
        });
        panelPengeluaran.add(txtLuarTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 380, -1));
        panelPengeluaran.add(txtLuarWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 380, -1));

        txtLuarCatatan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLuarCatatanFocusLost(evt);
            }
        });
        panelPengeluaran.add(txtLuarCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 380, -1));

        btnInput1.setBackground(new java.awt.Color(255, 255, 255));
        btnInput1.setForeground(new java.awt.Color(0, 153, 0));
        btnInput1.setText("Input");
        btnInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInput1ActionPerformed(evt);
            }
        });
        panelPengeluaran.add(btnInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 75, -1));

        btnReset1.setBackground(new java.awt.Color(255, 255, 255));
        btnReset1.setForeground(new java.awt.Color(204, 153, 0));
        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });
        panelPengeluaran.add(btnReset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 75, -1));

        jPanel7.setBackground(new java.awt.Color(90, 90, 205));
        jPanel7.setForeground(new java.awt.Color(23, 65, 127));

        lblJudul2.setBackground(new java.awt.Color(255, 255, 255));
        lblJudul2.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        lblJudul2.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul2.setText("Pengeluaran");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblJudul2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelPengeluaran.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 80));

        panelCari.setBackground(new java.awt.Color(255, 255, 255));
        panelCari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCari.setMinimumSize(new java.awt.Dimension(533, 356));
        panelCari.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbPengeluaran);
        rbPengeluaran.setText("Pengeluaran");
        rbPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPengeluaranActionPerformed(evt);
            }
        });
        panelCari.add(rbPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        rbPendapatan.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbPendapatan);
        rbPendapatan.setText("Pendapatan");
        rbPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPendapatanActionPerformed(evt);
            }
        });
        panelCari.add(rbPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        txtCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCariFocusLost(evt);
            }
        });
        panelCari.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 290, -1));

        btnCari_Cari.setBackground(new java.awt.Color(255, 255, 255));
        btnCari_Cari.setForeground(new java.awt.Color(51, 153, 0));
        btnCari_Cari.setText("Cari");
        btnCari_Cari.setMaximumSize(new java.awt.Dimension(65, 25));
        btnCari_Cari.setMinimumSize(new java.awt.Dimension(65, 25));
        btnCari_Cari.setPreferredSize(new java.awt.Dimension(65, 25));
        btnCari_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCari_CariActionPerformed(evt);
            }
        });
        panelCari.add(btnCari_Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 60, -1));

        lblCariPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCariPendapatan.setLabelFor(txtHapusPendapatan);
        lblCariPendapatan.setText("Pendapatan");
        panelCari.add(lblCariPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 120, -1));

        lblCari.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCari.setLabelFor(txtCariCatatan);
        lblCari.setText("Cari Catatan");
        panelCari.add(lblCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 120, -1));

        lblCariTanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCariTanggal.setLabelFor(txtPendapatan);
        lblCariTanggal.setText("Tanggal");
        panelCari.add(lblCariTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, -1));

        lblCariWaktu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCariWaktu.setLabelFor(txtCariWaktu);
        lblCariWaktu.setText("Waktu");
        panelCari.add(lblCariWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 120, -1));

        txtCariPendapatan.setEditable(false);
        panelCari.add(txtCariPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 290, -1));

        txtCariCatatan.setEditable(false);
        panelCari.add(txtCariCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 290, -1));

        txtCariTanggal.setEditable(false);
        panelCari.add(txtCariTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 290, -1));

        txtCariWaktu.setEditable(false);
        panelCari.add(txtCariWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 290, -1));

        lblCariCatatan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCariCatatan.setLabelFor(txtTanggal);
        lblCariCatatan.setText("Catatan");
        panelCari.add(lblCariCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, -1));

        jPanel3.setBackground(new java.awt.Color(23, 65, 117));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cari");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelCari.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 80));

        txtCariPEngeluaran.setEditable(false);
        panelCari.add(txtCariPEngeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 290, -1));

        lblCariPengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCariPengeluaran.setLabelFor(txtHapusPendapatan);
        lblCariPengeluaran.setText("Pengeluaran");
        panelCari.add(lblCariPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 120, -1));

        panelAwal.setBackground(new java.awt.Color(255, 255, 255));
        panelAwal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelAwal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelAwal.setMinimumSize(new java.awt.Dimension(372, 356));
        panelAwal.setName(""); // NOI18N
        panelAwal.setPreferredSize(new java.awt.Dimension(533, 356));
        panelAwal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(90, 90, 205));
        jPanel6.setForeground(new java.awt.Color(23, 65, 127));

        lblJudul1.setBackground(new java.awt.Color(255, 255, 255));
        lblJudul1.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        lblJudul1.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul1.setText("welcome");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblJudul1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelAwal.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 80));

        panelHapus.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHapus.setMinimumSize(new java.awt.Dimension(533, 356));
        panelHapus.setPreferredSize(new java.awt.Dimension(533, 356));
        panelHapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHapusPendapatan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHapusPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHapusPendapatan.setLabelFor(txtHapusPendapatan);
        lblHapusPendapatan.setText("Pendapatan");
        panelHapus.add(lblHapusPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelHapus.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        lblHapusTanggal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHapusTanggal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHapusTanggal.setLabelFor(txtHapusPengeluaran);
        lblHapusTanggal.setText("Tanggal");
        lblHapusTanggal.setToolTipText("");
        lblHapusTanggal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelHapus.add(lblHapusTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, -1));

        txtHapusPengeluaran.setEditable(false);
        txtHapusPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus.add(txtHapusPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 370, -1));

        txtHapusPendapatan.setEditable(false);
        txtHapusPendapatan.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus.add(txtHapusPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 189, 370, -1));

        lblHapusPengeluaran.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHapusPengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHapusPengeluaran.setLabelFor(txtPendapatan);
        lblHapusPengeluaran.setText("Pengeluaran");
        panelHapus.add(lblHapusPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        txtHapusTanggal.setEditable(false);
        txtHapusTanggal.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus.add(txtHapusTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 370, -1));

        txtHapusWaktu.setEditable(false);
        txtHapusWaktu.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus.add(txtHapusWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 370, -1));

        lblHapusWaktu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHapusWaktu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHapusWaktu.setLabelFor(txtHapusWaktu);
        lblHapusWaktu.setText("Waktu ");
        panelHapus.add(lblHapusWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 276, -1, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 153, 0));
        jButton2.setText("Reset");
        panelHapus.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jTabelHapus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabelHapus.setMaximumSize(new java.awt.Dimension(20, 256));
        jTabelHapus.setMinimumSize(new java.awt.Dimension(20, 256));
        jTabelHapus.setPreferredSize(new java.awt.Dimension(20, 256));
        jTabelHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelHapusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelHapus);

        panelHapus.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 470, 90));

        jPanel2.setBackground(new java.awt.Color(23, 65, 117));

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HAPUS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelHapus.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 80));

        lblHapusCatatan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHapusCatatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHapusCatatan.setLabelFor(txtHapusWaktu);
        lblHapusCatatan.setText("Catatan");
        panelHapus.add(lblHapusCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 30));

        txtHapusCatatan.setEditable(false);
        txtHapusCatatan.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus.add(txtHapusCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 370, -1));

        panelTampil.setBackground(new java.awt.Color(255, 255, 255));
        panelTampil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Waktu", "Pendapatan", "Pengeluaran"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel4.setBackground(new java.awt.Color(23, 65, 117));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Laporan Harian");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabelKosong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Total Pendapatan", "Total Pengeluaran", "Total Saldo"
            }
        ));
        jScrollPane3.setViewportView(jTabelKosong);

        javax.swing.GroupLayout panelTampilLayout = new javax.swing.GroupLayout(panelTampil);
        panelTampil.setLayout(panelTampilLayout);
        panelTampilLayout.setHorizontalGroup(
            panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTampilLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelTampilLayout.setVerticalGroup(
            panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTampilLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane3.setLayer(panelPendapatan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(panelPengeluaran, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(panelCari, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(panelAwal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(panelHapus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(panelTampil, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTampil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCari, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTampil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCari, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelPendapatan.getAccessibleContext().setAccessibleName("");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setMinimumSize(new java.awt.Dimension(106, 356));
        jPanel5.setPreferredSize(new java.awt.Dimension(106, 356));

        btnPendapatan.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnPendapatan.setText("Pendapatan");
        btnPendapatan.setMaximumSize(new java.awt.Dimension(70, 24));
        btnPendapatan.setMinimumSize(new java.awt.Dimension(70, 24));
        btnPendapatan.setPreferredSize(new java.awt.Dimension(70, 24));
        btnPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendapatanActionPerformed(evt);
            }
        });

        btnPengeluaran.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnPengeluaran.setText("Pengeluaran");
        btnPengeluaran.setMaximumSize(new java.awt.Dimension(70, 24));
        btnPengeluaran.setMinimumSize(new java.awt.Dimension(70, 24));
        btnPengeluaran.setPreferredSize(new java.awt.Dimension(70, 24));
        btnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengeluaranActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnCari.setText("Cari");
        btnCari.setMaximumSize(new java.awt.Dimension(70, 24));
        btnCari.setMinimumSize(new java.awt.Dimension(70, 24));
        btnCari.setPreferredSize(new java.awt.Dimension(70, 24));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnTampil.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnTampil.setText("Tampil");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setMaximumSize(new java.awt.Dimension(70, 24));
        btnHapus.setMinimumSize(new java.awt.Dimension(70, 24));
        btnHapus.setPreferredSize(new java.awt.Dimension(70, 24));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(btnPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTampil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengeluaranActionPerformed
        // icon.setVisible(false);
        panelCari.setVisible(false);
        panelTampil.setVisible(false);
        panelPendapatan.setVisible(false);
        panelHapus.setVisible(false);
        panelPengeluaran.setVisible(true);
        System.out.println(jTabelHapus.getSelectedRow());
        TampilData("Hapus", null);


    }//GEN-LAST:event_btnPengeluaranActionPerformed

    private void btnPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendapatanActionPerformed
        // icon.setVisible(false);
        lblTangga.setVisible(true);
        lblWaktu.setVisible(true);
        lblCatatan.setVisible(true);
        lblPendapatan.setVisible(true);
//        lblJenisKelamin.setVisible(true);
//        lblAlamat.setVisible(true);
//        lblLamaSewa.setVisible(true);
//        rbLakiLaki.setVisible(true);
//        rbPerempuan.setVisible(true);
        txtTanggal.setVisible(true);
        txtWaktu.setVisible(true);
        txtCatatan.setVisible(true);
        txtPendapatan.setVisible(true);
//        txtAlamat.setVisible(true);
//        txtLamaSewa.setVisible(true);
        btnInput.setVisible(true);
        lblJudul.setVisible(true);
        btnReset.setVisible(true);
        panelHapus.setVisible(false);
        panelCari.setVisible(false);
        panelTampil.setVisible(false);
        panelPendapatan.setVisible(true);
        panelAwal.setVisible(false);
        panelPengeluaran.setVisible(false);


    }//GEN-LAST:event_btnPendapatanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
//         icon.setVisible(false);
        panelHapus.setVisible(false);
        panelPendapatan.setVisible(false);
        panelTampil.setVisible(false);
        panelCari.setVisible(true);
        panelAwal.setVisible(false);
        panelPengeluaran.setVisible(false);


    }//GEN-LAST:event_btnCariActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // icon.setVisible(false);
        panelHapus.setVisible(false);
        panelPendapatan.setVisible(false);
        panelCari.setVisible(false);
        panelPengeluaran.setVisible(false);
        panelTampil.setVisible(true);
        TampilData("Tampil", null);
        TampilData("Tampil", "KamarKosong");

    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        if (datPen.sewa.size() < 16) {
            Penyewa pen;
            Menyewa sewa;
            String vnik = txtPendapatan.getText();
            String vnama = txtTanggal.getText();
//            String valamat = txtAlamat.getText();
            String vnoHp = txtWaktu.getText();
            int vnoKamar = Integer.parseInt(txtCatatan.getText());
//            int vlamaSewa = Integer.parseInt(txtLamaSewa.getText());
            //Object x, int index, Object obj, int jumlah
            int searchKamar = (int) sequentialSearch(vnoKamar, 0, datPen.kamarList, datPen.kamarList.size());
            if (datPen.kamarList.get(searchKamar).diSewa == false) {
//                if (rbLakiLaki.isSelected()) {
//                    if (datPen.haveValues("L") < 8) {
//                        //int NIK, String nama, String noHp, String jenis_kel
//                        pen = new Penyewa(vnik, vnama, vnoHp, "L");
//                        datPen.insertPenyewa(pen);
//                        sewa = new Menyewa(vnoKamar, vlamaSewa, "L", vnik, vnama, valamat);
//                        datPen.insertSewa(sewa);
//                        datPen.kamarList.get(searchKamar).setDiPinjam(true);
//
//                    } else {
//                        JOptionPane.showMessageDialog(this, "Kost Laki - Laki Penuh");
//                    }
//                } else if (rbPerempuan.isSelected()) {
//                    if (datPen.haveValues("P") < 8) {
//                        pen = new Penyewa(vnik, vnama, vnoHp, "P");
//                        datPen.insertPenyewa(pen);
//                        sewa = new Menyewa(vnoKamar, vlamaSewa, "L", vnik, vnama, valamat);;
//                        datPen.insertSewa(sewa);
//                        datPen.kamarList.get(searchKamar).setDiPinjam(true);
//                    } else {
//                        JOptionPane.showMessageDialog(this, "Kost Perempuan Penuh");
//                    }
//                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Kamar sudah tersewa", "Peringatan", JOptionPane.ERROR_MESSAGE);
        }

        clrInput("Tambah");

    }//GEN-LAST:event_btnInputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a = jTabelHapus.getSelectedRow();
        if (a >= 0) {
            datPen.sewa.remove(a);
            datPen.penyewaList.remove(a);
            TampilData("Hapus", null);
            JOptionPane.showMessageDialog(this, "Data Berhasil DiHapus", "Success", JOptionPane.INFORMATION_MESSAGE);
            clrInput("Hapus");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabelHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelHapusMouseClicked
        if (jTabelHapus.getSelectedRow() >= 0) {
            int indexTabel = jTabelHapus.getSelectedRow();
            txtHapusPendapatan.setText(Integer.toString(datPen.sewa.get(indexTabel).nokost));
            txtHapusTanggal.setText(datPen.sewa.get(indexTabel).nama);
            txtHapusWaktu.setText(datPen.sewa.get(indexTabel).alamat);
            txtHapusPengeluaran.setText(datPen.sewa.get(indexTabel).nik);
        }
    }//GEN-LAST:event_jTabelHapusMouseClicked

    private void txtPendapatanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPendapatanFocusLost
        if (txtPendapatan.getText().equals("")) {
            return;
        }
        cek(txtPendapatan.getText(), txtPendapatan);
    }//GEN-LAST:event_txtPendapatanFocusLost

    private void txtTanggalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTanggalFocusLost
        if (txtTanggal.getText().equals("")) {
            return;
        }
        cek(txtTanggal.getText(), txtTanggal);
    }//GEN-LAST:event_txtTanggalFocusLost

    private void txtCatatanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCatatanFocusLost
        if (txtCatatan.getText().equals("")) {
            return;
        }
        cek(txtCatatan.getText(), txtCatatan);
    }//GEN-LAST:event_txtCatatanFocusLost

    private void btnCari_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari_CariActionPerformed

        if ((!txtCari.getText().equals("") || txtCari != null) && cek(txtCari.getText(), txtCari)) {
            String cari = txtCari.getText();
            int car = (int) sequentialSearch(cari, 0, datPen.sewa, datPen.sewa.size());
            if (car < 0) {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Harap Isi Pencarian dlu");
        }


    }//GEN-LAST:event_btnCari_CariActionPerformed

    private void txtCariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariFocusLost
//        if(rbNomorKamar.isSelected()){
//            if(!txtCari.getText().matches("[0-9]+")){
//                JOptionPane.showMessageDialog(this, "Data Harus Berupa Angka");
//                clrInput("Cari");
//            }
//        }else{
//            if(txtCari.getText().matches(".*\\d.*")){
//                JOptionPane.showMessageDialog(this, "Nama Tidak Boleh Mengandung Angka");
//                clrInput("Cari");
//            }
//            
//        }

    }//GEN-LAST:event_txtCariFocusLost

    private void txtPengeluaranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPengeluaranFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPengeluaranFocusLost

    private void txtLuarTanggalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLuarTanggalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuarTanggalFocusLost

    private void txtLuarCatatanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLuarCatatanFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuarCatatanFocusLost

    private void btnInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInput1ActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void txtLuarTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuarTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuarTanggalActionPerformed

    private void rbPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPendapatanActionPerformed
        if (rbPendapatan.isSelected()) {
            lblCari.setText("Nama Penyewa");
        }
    }//GEN-LAST:event_rbPendapatanActionPerformed

    private void rbPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPengeluaranActionPerformed
        if (rbPengeluaran.isSelected()) {
            lblCari.setText("No Kamar");
        }
    }//GEN-LAST:event_rbPengeluaranActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        panelHapus.setVisible(true);
        panelPendapatan.setVisible(false);
        panelPengeluaran.setVisible(false);
        panelTampil.setVisible(false);
        panelCari.setVisible(false);
        panelAwal.setVisible(false);
    }//GEN-LAST:event_btnHapusActionPerformed

    public void hideComponent() {
        panelHapus.setVisible(false);
        panelPengeluaran.setVisible(false);
        panelPendapatan.setVisible(false);
        panelCari.setVisible(false);
        panelTampil.setVisible(false);

    }

    public void tambahDataKost() {
        Kost kst[] = new Kost[2];
        kst[0] = new Kost(1, 8, "Paingan", "L");
        kst[1] = new Kost(2, 8, "Mrican", "P");
        datPen.kostList.add(kst[0]);
        datPen.kostList.add(kst[1]);
    }

    public void tambahDataKamarKost() {
        KamarKost kk[] = new KamarKost[16];
        for (int i = 0; i < kk.length; i++) {
            if (i < 7) {
                kk[i] = new KamarKost(i + 1, 600000, datPen.kostList.get(0), false);
                datPen.insertKamar(kk[i]);
            } else {
                kk[i] = new KamarKost(i + 1, 650000, datPen.kostList.get(1), false);
                datPen.insertKamar(kk[i]);
            }
        }
    }

    private void clrInput(String jenis) {
        if ("Tambah".equals(jenis)) {
            txtPendapatan.setText("");
            txtTanggal.setText("");
            txtWaktu.setText("");
            txtCatatan.setText("");
//            txtAlamat.setText("");
//            txtLamaSewa.setText("");
        } else if (jenis.equals("Hapus")) {
            txtHapusWaktu.setText("");
            txtHapusPengeluaran.setText("");
            txtHapusTanggal.setText("");
            txtHapusPendapatan.setText("");
        } else if (jenis.equals("Cari")) {
            txtCari.setText("");
        }

    }

    /*Di button cari ini akan menjalan pencarian dengan menggunakan metode searchong objek
    dengan cara sequential search, seperti berikut. Kami membuat metode sequential search dengan parameter .......
    di metode ini akan dilakukan percabangan yang dimana ketika indek kurang dari jumlah
    maka masuk ke percabangan lafi dengan parameterr .... maka akan masuk ke percabangan ketika
    user memilih rb nama penyewa, maka akan dicek apakah....*/
    Object sequentialSearch(Object x, int index, Object obj, int jumlah) {
        int jum = -1;
        if (index < jumlah) {
            if (obj == datPen.sewa) {
                if (rbPendapatan.isSelected()) {
                    //Parameter obj sama dengan isi dari array list sewa yang disimpan dalam kelas datakost yang diakses menggunakan nama objek datPen
                    if (((String) x).equalsIgnoreCase(datPen.sewa.get(index).nama)) {
                        jum = 0;
                        //Ketika percabangan ini bernilai benar maka indeknya akan disimpan dan datanya akan ditampilkan
                        TampilDataCari(index);
                    } else {
                        //Jika tidak maka indeknya akan bertambah satu sesuai dengan model sequential dan metode ini akan dipanggil kembali

                        index++;
                        return sequentialSearch(x, index, obj, jumlah);
                    }
                } else { //No Kamar                    
                    if (Integer.parseInt(((String) x)) == datPen.sewa.get(index).nokost) {
                        jum = 0;
                        TampilDataCari(index);
                    } else {
                        index++;
                        return sequentialSearch(x, index, obj, jumlah);
                    }
                }
            } else if (obj == datPen.kamarList) {
                if (((int) x) == datPen.kamarList.get(index).no_kost) {
                    return index;
                } else {
                    index++;
                    return sequentialSearch(x, index, obj, jumlah);
                }
            }
        } else if (index == jumlah - 1 && jum != 0) {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return jum;
    }

    public void TampilDataCari(int i) {
        txtCariCatatan.setText(datPen.sewa.get(i).nama);
        txtCariWaktu.setText(datPen.sewa.get(i).alamat);
        txtCariTanggal.setText(datPen.sewa.get(i).nik);
        txtCariPendapatan.setText(Integer.toString(datPen.sewa.get(i).nokost));
    }

    public void tambahDataPenyewaMenyewa() {
        Menyewa sewa;
        Penyewa pen;

        pen = new Penyewa("3404093092022321", "Abdi", "0895391616312", "L");
        datPen.insertPenyewa(pen);
        pen = new Penyewa("3404093092022211", "Sang", "0895391226312", "L");
        datPen.insertPenyewa(pen);
        pen = new Penyewa("3404093092022661", "Savia", "0895391616112", "P");
        datPen.insertPenyewa(pen);

        sewa = new Menyewa(datPen.kamarList.get(0).no_kost, 5, datPen.penyewaList.get(0).jenis_kel, datPen.penyewaList.get(0).NIK, datPen.penyewaList.get(0).nama, datPen.kostList.get(0).alamat);
        datPen.insertSewa(sewa);

        sewa = new Menyewa(datPen.kamarList.get(1).no_kost, 5, datPen.penyewaList.get(1).jenis_kel, datPen.penyewaList.get(1).NIK, datPen.penyewaList.get(1).nama, datPen.kostList.get(0).alamat);
        datPen.insertSewa(sewa);
        sewa = new Menyewa(datPen.kamarList.get(0).no_kost, 5, datPen.penyewaList.get(2).jenis_kel, datPen.penyewaList.get(2).NIK, datPen.penyewaList.get(2).nama, datPen.kostList.get(1).alamat);
        datPen.insertSewa(sewa);
    }

    public void TampilData(String jenis, String jenisKel) {
        String[] namaKolom = {"No_kost", "Nama", "Kategori", "Lama Sewa"};
        tabelModel tblModel;
        if (jenis.equals("Hapus")) {
            tblModel = new tabelModel(namaKolom, datPen, jenisKel);
            jTabelHapus.setModel(tblModel);
            jTabelHapus.revalidate();
        } else if (jenis.equals("Tampil")) {
            if (jenisKel == null) {
                tblModel = new tabelModel(namaKolom, datPen, jenisKel);
                jTable2.setModel(tblModel);
                jTable2.revalidate();
            } else if (jenisKel.equals("KamarKosong")) {
                String[] kolKosong = {"No Kamar", "Kategori", "Alamat", "Harga Sewa"};
                tblModel = new tabelModel(kolKosong, datPen, jenisKel);
                jTabelKosong.setModel(tblModel);
                jTable2.revalidate();
            }

        }

    }

    public Boolean cek(Object cek, JTextField txt) {
        try {
            if (txt == txtTanggal) {
                if (!((String) cek).matches(".*\\d.*")) {
                    txtTanggal.setText((String) cek);
                } else {
                    throw new Exception("Nama tidak boleh berisi nomor");
                }
            } else if (txt == txtPendapatan) {
                if (((String) cek).matches("[0-9]+")) {
                    txtPendapatan.setText(((String) cek));
                } else {
                    throw new Exception("NIK Hanya Boleh Berisi Angka");
                }
//            } else if (txt == txtAlamat) {
//                if (((String) cek).matches("[0-9]+")) {
//                    txtAlamat.setText(((String) cek));
//                } else {
//                    throw new Exception("NIK Hanya Boleh Berisi Angka");
//                }
            } else if (txt == txtCatatan) {
                if (((String) cek).matches("[0-9]+")) {
                    txtCatatan.setText(((String) cek));
                } else {
                    throw new Exception("NIK Hanya Boleh Berisi Angka");
                }
            } else if (txt == txtCari) {
                if (rbPengeluaran.isSelected()) {
                    if (((String) cek).matches("[0-9]+")) {
                        txtCari.setText((String) cek);
                        return true;
                    } else {
                        throw new Exception("Nomor kamar harus berupa angka");
                    }
                } else if (rbPendapatan.isSelected()) {
                    if (!((String) cek).matches(".*\\d.*")) {
                        txtCari.setText((String) cek);
                        return true;
                    } else {
                        throw new Exception("Nama tidak boleh mengandung angka");
                    }
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "PERINGATAN", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenuAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCari_Cari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnInput1;
    private javax.swing.JButton btnPendapatan;
    private javax.swing.JButton btnPengeluaran;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnTampil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabelHapus;
    private javax.swing.JTable jTabelKosong;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblCariCatatan;
    private javax.swing.JLabel lblCariPendapatan;
    private javax.swing.JLabel lblCariPengeluaran;
    private javax.swing.JLabel lblCariTanggal;
    private javax.swing.JLabel lblCariWaktu;
    private javax.swing.JLabel lblCatatan;
    private javax.swing.JLabel lblHapusCatatan;
    private javax.swing.JLabel lblHapusPendapatan;
    private javax.swing.JLabel lblHapusPengeluaran;
    private javax.swing.JLabel lblHapusTanggal;
    private javax.swing.JLabel lblHapusWaktu;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul1;
    private javax.swing.JLabel lblJudul2;
    private javax.swing.JLabel lblLuarCatatan;
    private javax.swing.JLabel lblLuarTanggal;
    private javax.swing.JLabel lblLuarWaktu;
    private javax.swing.JLabel lblPendapatan;
    private javax.swing.JLabel lblPendapatan1;
    private javax.swing.JLabel lblTangga;
    private javax.swing.JLabel lblWaktu;
    private javax.swing.JPanel panelAwal;
    private javax.swing.JPanel panelCari;
    private javax.swing.JPanel panelHapus;
    private javax.swing.JPanel panelPendapatan;
    private javax.swing.JPanel panelPengeluaran;
    private javax.swing.JPanel panelTampil;
    private javax.swing.JRadioButton rbPendapatan;
    private javax.swing.JRadioButton rbPengeluaran;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtCariCatatan;
    private javax.swing.JTextField txtCariPEngeluaran;
    private javax.swing.JTextField txtCariPendapatan;
    private javax.swing.JTextField txtCariTanggal;
    private javax.swing.JTextField txtCariWaktu;
    private javax.swing.JTextField txtCatatan;
    private javax.swing.JTextField txtHapusCatatan;
    private javax.swing.JTextField txtHapusPendapatan;
    private javax.swing.JTextField txtHapusPengeluaran;
    private javax.swing.JTextField txtHapusTanggal;
    private javax.swing.JTextField txtHapusWaktu;
    private javax.swing.JTextField txtLuarCatatan;
    private javax.swing.JTextField txtLuarTanggal;
    private javax.swing.JTextField txtLuarWaktu;
    private javax.swing.JTextField txtPendapatan;
    private javax.swing.JTextField txtPengeluaran;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtWaktu;
    // End of variables declaration//GEN-END:variables
}
