/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDNLFIX;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class GuiMenuAwal extends javax.swing.JFrame {

    Tree pohon;
    TreeNode node;
    DefaultTableModel tableModel;
    TableColumnModel columnModel;
    ArrayList<DataPengeluaran> dat;

    public GuiMenuAwal() {
        node = new TreeNode();
        pohon = new Tree();
        initComponents();
        hideComponent();
        tambahDataPengeluaran();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        panelPengeluaran = new javax.swing.JPanel();
        lblPengeluaran = new javax.swing.JLabel();
        lblTangga = new javax.swing.JLabel();
        lblWaktu = new javax.swing.JLabel();
        lblCatatan = new javax.swing.JLabel();
        txtPengeluaran = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        txtWaktu = new javax.swing.JTextField();
        txtCatatan = new javax.swing.JTextField();
        btnInputPengeluaran = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        panelAwal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelCari = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        btnCari_Cari = new javax.swing.JButton();
        lblCari = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabelCari = new javax.swing.JTable();
        panelHapus = new javax.swing.JPanel();
        HapusBtn = new javax.swing.JButton();
        lblHapusTanggal = new javax.swing.JLabel();
        txtHapusPengeluaran = new javax.swing.JTextField();
        lblHapusPengeluaran = new javax.swing.JLabel();
        txtHapusTanggal = new javax.swing.JTextField();
        txtHapusWaktu = new javax.swing.JTextField();
        lblHapusWaktu = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelHapus = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblHapusCatatan = new javax.swing.JLabel();
        txtHapusCatatan = new javax.swing.JTextField();
        panelTampil = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelLaporanHarian1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnPengeluaran = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();

        jScrollPane4.setViewportView(jTextPane1);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 65, 95));

        jLayeredPane3.setMinimumSize(new java.awt.Dimension(533, 356));

        panelPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        panelPengeluaran.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPengeluaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPengeluaran.setMinimumSize(new java.awt.Dimension(372, 356));
        panelPengeluaran.setName(""); // NOI18N
        panelPengeluaran.setPreferredSize(new java.awt.Dimension(533, 356));
        panelPengeluaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPengeluaran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPengeluaran.setLabelFor(txtPengeluaran);
        lblPengeluaran.setText("Pengeluaran");
        panelPengeluaran.add(lblPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        lblTangga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTangga.setLabelFor(txtTanggal);
        lblTangga.setText("Tanggal");
        lblTangga.setToolTipText("");
        panelPengeluaran.add(lblTangga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        lblWaktu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblWaktu.setLabelFor(txtWaktu);
        lblWaktu.setText("Waktu");
        panelPengeluaran.add(lblWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lblCatatan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCatatan.setLabelFor(txtCatatan);
        lblCatatan.setText("Catatan");
        panelPengeluaran.add(lblCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        txtPengeluaran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPengeluaranFocusLost(evt);
            }
        });
        panelPengeluaran.add(txtPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 380, -1));

        txtTanggal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTanggalFocusLost(evt);
            }
        });
        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });
        panelPengeluaran.add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 380, -1));
        panelPengeluaran.add(txtWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 380, -1));

        txtCatatan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCatatanFocusLost(evt);
            }
        });
        panelPengeluaran.add(txtCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 380, -1));

        btnInputPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        btnInputPengeluaran.setForeground(new java.awt.Color(0, 153, 0));
        btnInputPengeluaran.setText("Input");
        btnInputPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputPengeluaranActionPerformed(evt);
            }
        });
        panelPengeluaran.add(btnInputPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 75, -1));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setForeground(new java.awt.Color(204, 153, 0));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        panelPengeluaran.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 75, -1));

        jPanel1.setBackground(new java.awt.Color(90, 90, 205));
        jPanel1.setForeground(new java.awt.Color(23, 65, 127));

        lblJudul.setBackground(new java.awt.Color(255, 255, 255));
        lblJudul.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("pengeluaran");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblJudul)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelPengeluaran.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 80));

        panelAwal.setBackground(new java.awt.Color(255, 255, 255));
        panelAwal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelAwal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelAwal.setMinimumSize(new java.awt.Dimension(372, 356));
        panelAwal.setName(""); // NOI18N
        panelAwal.setPreferredSize(new java.awt.Dimension(533, 356));
        panelAwal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDNLFIX/Logo2.png"))); // NOI18N
        panelAwal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        panelCari.setBackground(new java.awt.Color(255, 255, 255));
        panelCari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCari.setMinimumSize(new java.awt.Dimension(533, 356));
        panelCari.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCariFocusLost(evt);
            }
        });
        panelCari.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 290, -1));

        btnCari_Cari.setBackground(new java.awt.Color(255, 255, 255));
        btnCari_Cari.setForeground(new java.awt.Color(51, 153, 0));
        btnCari_Cari.setText("Cari");
        btnCari_Cari.setMaximumSize(new java.awt.Dimension(65, 25));
        btnCari_Cari.setMinimumSize(new java.awt.Dimension(65, 25));
        btnCari_Cari.setPreferredSize(new java.awt.Dimension(65, 25));
        btnCari_Cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCari_CariFocusLost(evt);
            }
        });
        btnCari_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCari_CariActionPerformed(evt);
            }
        });
        panelCari.add(btnCari_Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 60, -1));

        lblCari.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCari.setText("Cari Pengeluaran");
        panelCari.add(lblCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, -1));

        jPanel3.setBackground(new java.awt.Color(90, 90, 205));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cari");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelCari.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 80));

        jTabelCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Waktu", "Pengeluaran"
            }
        ));
        jTabelCari.setMaximumSize(new java.awt.Dimension(20, 256));
        jTabelCari.setMinimumSize(new java.awt.Dimension(20, 256));
        jTabelCari.setPreferredSize(new java.awt.Dimension(20, 256));
        jTabelCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelCariMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabelCariMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTabelCari);

        panelCari.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 470, 90));

        panelHapus.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHapus.setMinimumSize(new java.awt.Dimension(533, 356));
        panelHapus.setPreferredSize(new java.awt.Dimension(533, 356));
        panelHapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HapusBtn.setBackground(new java.awt.Color(255, 255, 255));
        HapusBtn.setForeground(new java.awt.Color(0, 204, 0));
        HapusBtn.setText("Hapus");
        HapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusBtnActionPerformed(evt);
            }
        });
        panelHapus.add(HapusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        lblHapusTanggal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHapusTanggal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHapusTanggal.setLabelFor(txtHapusPengeluaran);
        lblHapusTanggal.setText("Tanggal");
        lblHapusTanggal.setToolTipText("");
        lblHapusTanggal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelHapus.add(lblHapusTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 50, -1));

        txtHapusPengeluaran.setEditable(false);
        txtHapusPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus.add(txtHapusPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 370, -1));

        lblHapusPengeluaran.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHapusPengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHapusPengeluaran.setLabelFor(txtPengeluaran);
        lblHapusPengeluaran.setText("Pengeluaran");
        panelHapus.add(lblHapusPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        txtHapusTanggal.setEditable(false);
        txtHapusTanggal.setBackground(new java.awt.Color(255, 255, 255));
        txtHapusTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHapusTanggalActionPerformed(evt);
            }
        });
        panelHapus.add(txtHapusTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 370, -1));

        txtHapusWaktu.setEditable(false);
        txtHapusWaktu.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus.add(txtHapusWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 370, -1));

        lblHapusWaktu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHapusWaktu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHapusWaktu.setLabelFor(txtHapusWaktu);
        lblHapusWaktu.setText("Waktu ");
        panelHapus.add(lblHapusWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 276, -1, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 153, 0));
        jButton2.setText("Reset");
        panelHapus.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jTabelHapus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Waktu", "Pengeluaran"
            }
        ));
        jTabelHapus.setMaximumSize(new java.awt.Dimension(20, 256));
        jTabelHapus.setMinimumSize(new java.awt.Dimension(20, 256));
        jTabelHapus.setPreferredSize(new java.awt.Dimension(20, 256));
        jTabelHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelHapusMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabelHapusMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelHapus);

        panelHapus.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 470, 90));

        jPanel2.setBackground(new java.awt.Color(90, 90, 205));

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HAPUS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelHapus.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 80));

        lblHapusCatatan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHapusCatatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHapusCatatan.setLabelFor(txtHapusWaktu);
        lblHapusCatatan.setText("Catatan");
        panelHapus.add(lblHapusCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 30));

        txtHapusCatatan.setEditable(false);
        txtHapusCatatan.setBackground(new java.awt.Color(255, 255, 255));
        panelHapus.add(txtHapusCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 370, -1));

        panelTampil.setBackground(new java.awt.Color(255, 255, 255));
        panelTampil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTampil.setPreferredSize(new java.awt.Dimension(533, 356));

        TabelLaporanHarian1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tanggal", "Waktu", "Pengeluaran"
            }
        ));
        jScrollPane2.setViewportView(TabelLaporanHarian1);

        jPanel4.setBackground(new java.awt.Color(90, 90, 205));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Laporan Harian");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTampilLayout = new javax.swing.GroupLayout(panelTampil);
        panelTampil.setLayout(panelTampilLayout);
        panelTampilLayout.setHorizontalGroup(
            panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTampilLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelTampilLayout.setVerticalGroup(
            panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTampilLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jLayeredPane3.setLayer(panelPengeluaran, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(panelAwal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(panelCari, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(panelHapus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(panelTampil, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTampil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCari, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addComponent(panelHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTampil, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCari, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelPengeluaran.getAccessibleContext().setAccessibleName("");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setMinimumSize(new java.awt.Dimension(106, 356));
        jPanel5.setPreferredSize(new java.awt.Dimension(106, 356));

        btnPengeluaran.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnPengeluaran.setText("Pengeluaran");
        btnPengeluaran.setMaximumSize(new java.awt.Dimension(70, 24));
        btnPengeluaran.setMinimumSize(new java.awt.Dimension(70, 24));
        btnPengeluaran.setPreferredSize(new java.awt.Dimension(70, 24));
        btnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengeluaranActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnCari.setText("Cari");
        btnCari.setMaximumSize(new java.awt.Dimension(70, 24));
        btnCari.setMinimumSize(new java.awt.Dimension(70, 24));
        btnCari.setPreferredSize(new java.awt.Dimension(70, 24));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnTampil.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnTampil.setText("Tampil");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setMaximumSize(new java.awt.Dimension(70, 24));
        btnHapus.setMinimumSize(new java.awt.Dimension(70, 24));
        btnHapus.setPreferredSize(new java.awt.Dimension(70, 24));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SDNLFIX/Logo.png"))); // NOI18N
        lblIcon.setText("jLabel1");
        lblIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTampil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengeluaranActionPerformed

        lblTangga.setVisible(true);
        lblWaktu.setVisible(true);
        lblCatatan.setVisible(true);
        lblPengeluaran.setVisible(true);
        txtTanggal.setVisible(true);
        txtWaktu.setVisible(true);
        txtCatatan.setVisible(true);
        txtPengeluaran.setVisible(true);
        btnInputPengeluaran.setVisible(true);
        btnReset.setVisible(true);
        panelHapus.setVisible(false);
        panelCari.setVisible(false);
        panelTampil.setVisible(false);
        panelPengeluaran.setVisible(true);
        panelAwal.setVisible(false);
    }//GEN-LAST:event_btnPengeluaranActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed

        panelHapus.setVisible(false);
        panelTampil.setVisible(false);
        panelCari.setVisible(true);
        panelAwal.setVisible(false);
        panelPengeluaran.setVisible(false);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed

        panelHapus.setVisible(false);
        panelPengeluaran.setVisible(false);
        panelCari.setVisible(false);
        panelTampil.setVisible(true);
        TampilData("Tampil");

    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnInputPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputPengeluaranActionPerformed

        String vCatatan = txtCatatan.getText();
        String vTanggal = txtTanggal.getText();
        String vWaktu = txtWaktu.getText();
        int vPengeluaran = Integer.parseInt(txtPengeluaran.getText());

        DataPengeluaran data = new DataPengeluaran(vTanggal, vWaktu, vCatatan, vPengeluaran);
        pohon.insertNode(data);
        JOptionPane.showMessageDialog(this, "Data Berhasil Ditambah", "Success", JOptionPane.INFORMATION_MESSAGE);

        clrInput("Tambah");

    }//GEN-LAST:event_btnInputPengeluaranActionPerformed

    private void HapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusBtnActionPerformed
        int a = jTabelHapus.getSelectedRow();
        if (a >= 0) {
            System.out.println("Data : " + pohon.getRoot().getData().getPengeluaran());
            DataPengeluaran selectedData = dat.get(a);
            pohon.delete(selectedData);
            dat.remove(a);
            JOptionPane.showMessageDialog(this, "Data Berhasil DiHapus", "Success", JOptionPane.INFORMATION_MESSAGE);
            TampilData("Hapus");
            clrInput("Hapus");
        }
    }//GEN-LAST:event_HapusBtnActionPerformed

    private void jTabelHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelHapusMouseClicked
        if (jTabelHapus.getSelectedRow() >= 0) {
            int indexTabel = jTabelHapus.getSelectedRow();

            txtHapusCatatan.setText(dat.get(indexTabel).getCatatan());
            txtHapusTanggal.setText(dat.get(indexTabel).getTanggal());
            txtHapusWaktu.setText(dat.get(indexTabel).getWaktu());
            txtHapusPengeluaran.setText(Integer.toString(dat.get(indexTabel).getPengeluaran()));

        }
    }//GEN-LAST:event_jTabelHapusMouseClicked

    private void txtPengeluaranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPengeluaranFocusLost
        if (txtPengeluaran.getText().equals("")) {
            return;
        }
        cek(txtPengeluaran.getText(), txtPengeluaran);
    }//GEN-LAST:event_txtPengeluaranFocusLost

    private void txtTanggalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTanggalFocusLost
        if (txtTanggal.getText().equals("")) {
            return;
        }
        cek(txtTanggal.getText(), txtTanggal);
    }//GEN-LAST:event_txtTanggalFocusLost

    private void txtCatatanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCatatanFocusLost
        if (txtCatatan.getText().equals("")) {
            return;
        }
        cek(txtCatatan.getText(), txtCatatan);
    }//GEN-LAST:event_txtCatatanFocusLost

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        panelHapus.setVisible(true);
        panelPengeluaran.setVisible(false);
        panelPengeluaran.setVisible(false);
        panelTampil.setVisible(false);
        panelCari.setVisible(false);
        panelAwal.setVisible(false);
        TampilData("Hapus");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void lblIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconMouseClicked
        panelHapus.setVisible(false);
        panelPengeluaran.setVisible(false);
        panelPengeluaran.setVisible(false);
        panelCari.setVisible(false);
        panelTampil.setVisible(false);
        panelAwal.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_lblIconMouseClicked

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void jTabelHapusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelHapusMouseReleased

    }//GEN-LAST:event_jTabelHapusMouseReleased

    private void txtHapusTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHapusTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHapusTanggalActionPerformed

    private void btnCari_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari_CariActionPerformed
        // Cek textbox kosong dan simpan data inputan
        if (!txtCari.getText().isEmpty()) {
            int cari = Integer.parseInt(txtCari.getText());

            DataPengeluaran cariP = new DataPengeluaran(cari);
            TreeNode hasilPencarian = pohon.search(cariP);

            if (hasilPencarian != null) { // Memeriksa apakah data ditemukan dalam pohon
                TampilDataCari("Cari", cari);
                JOptionPane.showMessageDialog(this, "Data Ditemukan");
            } else {
                JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Harap isi pencarian terlebih dahulu");
        }

    }//GEN-LAST:event_btnCari_CariActionPerformed

    private void txtCariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariFocusLost
        if (txtCari.getText().equals("")) {
            return;
        }
        cek(txtCari.getText(), txtCari);

    }//GEN-LAST:event_txtCariFocusLost

    private void jTabelCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelCariMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabelCariMouseClicked

    private void jTabelCariMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelCariMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabelCariMouseReleased

    private void btnCari_CariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCari_CariFocusLost
       if (txtCari.getText().equals("")) {
            return;
        }
        cek(txtCari.getText(), txtCari);

    }//GEN-LAST:event_btnCari_CariFocusLost

//    Metode ini untuk hide GUI, jadi hanya panelAwal saja yang ditampilkan
//    terlebih dahulu
    public void hideComponent() {
        panelHapus.setVisible(false);
        panelPengeluaran.setVisible(false);
        panelPengeluaran.setVisible(false);
        panelCari.setVisible(false);
        panelTampil.setVisible(false);

    }
//    Hapus isi texbox

    private void clrInput(String jenis) {
        if ("Tambah".equals(jenis)) {
            txtPengeluaran.setText("");
            txtTanggal.setText("");
            txtWaktu.setText("");
            txtCatatan.setText("");
        } else if (jenis.equals("Hapus")) {
            txtHapusWaktu.setText("");
            txtHapusPengeluaran.setText("");
            txtHapusTanggal.setText("");
            txtHapusPengeluaran.setText("");
        } else if (jenis.equals("Cari")) {
            txtCari.setText("");
        }

    }

    public void TampilDataCari(String jenis, int cari) {
        String[] namaKolom = {"Tanggal", "Waktu", "Catatan", "Pengeluaran"};
        tableModel = new DefaultTableModel(namaKolom, 0) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jTabelCari.revalidate();
        jTabelCari.repaint();
        dat = new ArrayList();

        // Panggil metode traverseTree dengan root node pohon dan tblModel
        inOrderTraverse(pohon.getRoot(), tableModel, dat);

        if (jenis.equals("Cari")) {
            int kataKunci = cari;
            DefaultTableModel filteredModel = new DefaultTableModel(namaKolom, 0) {
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return false;
                }
            };

            // Loop melalui data yang ditemukan dan tambahkan data difilter
            for (DataPengeluaran data : dat) {

                String catatan = data.getCatatan();
                int pengeluaran = data.getPengeluaran();

                if (pengeluaran == kataKunci) {

                    Object[] row = {data.getTanggal(), data.getWaktu(), catatan, pengeluaran};
                    filteredModel.addRow(row);
                }
            }

            jTabelCari.setModel(filteredModel);
        }
    }

    public void tambahDataPengeluaran() {

        DataPengeluaran data1 = new DataPengeluaran("13 Mei 2023", "9 Pagi", "Yogtan", 999999);
        DataPengeluaran data2 = new DataPengeluaran("13 Mei 2023", "12 Pagi", "Nasi Padang", 120000);
        DataPengeluaran data3 = new DataPengeluaran("13 Mei 2023", "10 Pagi", "Nasi Ayam", 20000);

        pohon.insertNode(data1);
        pohon.insertNode(data2);
        pohon.insertNode(data3);

    }

    public void TampilData(String jenis) {
        String[] namaKolom = {"Tanggal", "Waktu", "Catatan", "Pengeluaran"};
        tableModel = new DefaultTableModel(namaKolom, 0) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        TabelLaporanHarian1.revalidate();
        TabelLaporanHarian1.repaint();
        dat = new ArrayList();

        // Panggil metode traverseTree dengan root node pohon dan tblModel
        inOrderTraverse(pohon.getRoot(), tableModel, dat);
        if (jenis.equals("Tampil")) {
            TabelLaporanHarian1.setModel(tableModel);
        } else if (jenis.equals("Hapus")) {
            jTabelHapus.setModel(tableModel);
        }
    }

    // Metode traverseTree untuk mengisi data dari pohon ke dalam tabel
    private void inOrderTraverse(TreeNode node, DefaultTableModel tblModel, ArrayList<DataPengeluaran> dat) {
        if (node != null) {
            inOrderTraverse(node.getLeftNode(), tblModel, dat);
            dat.add(node.getData());
            Object[] rowData = {node.getData().getTanggal(), node.getData().getWaktu(), node.getData().getCatatan(), node.getData().getPengeluaran()};
            tblModel.addRow(rowData);
            inOrderTraverse(node.getRightNode(), tblModel, dat);
        }
    }

    public Boolean cek(Object cek, JTextField txt) {
        try {

            if (txt == txtCari) {
                if (((String) cek).matches("[0-9]+")) {
                    txtCari.setText(((String) cek));
                } else {
                    throw new Exception("NIK Hanya Boleh Berisi Angka");
                }

            } else if (txt == txtPengeluaran) {
                if (((String) cek).matches("[0-9]+")) {
                    txtPengeluaran.setText(((String) cek));
                } else {
                    throw new Exception("NIK Hanya Boleh Berisi Angka");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "PERINGATAN", JOptionPane.ERROR_MESSAGE);
        }

        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenuAwal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenuAwal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenuAwal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenuAwal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenuAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HapusBtn;
    private javax.swing.JTable TabelLaporanHarian1;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCari_Cari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnInputPengeluaran;
    private javax.swing.JButton btnPengeluaran;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTampil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTabelCari;
    private javax.swing.JTable jTabelHapus;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblCatatan;
    private javax.swing.JLabel lblHapusCatatan;
    private javax.swing.JLabel lblHapusPengeluaran;
    private javax.swing.JLabel lblHapusTanggal;
    private javax.swing.JLabel lblHapusWaktu;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblPengeluaran;
    private javax.swing.JLabel lblTangga;
    private javax.swing.JLabel lblWaktu;
    private javax.swing.JPanel panelAwal;
    private javax.swing.JPanel panelCari;
    private javax.swing.JPanel panelHapus;
    private javax.swing.JPanel panelPengeluaran;
    private javax.swing.JPanel panelTampil;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtCatatan;
    private javax.swing.JTextField txtHapusCatatan;
    private javax.swing.JTextField txtHapusPengeluaran;
    private javax.swing.JTextField txtHapusTanggal;
    private javax.swing.JTextField txtHapusWaktu;
    private javax.swing.JTextField txtPengeluaran;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtWaktu;
    // End of variables declaration//GEN-END:variables
}
